### ISSUE TITLE
Problème pluie

### ISSUE THREAD

**Issue by gablaxy** [az4aaz/plue#1]
Si on vient d'arriver sur la page (e.g on la refresh) et qu'on ne scroll pas, la pluie ne s'affiche pas.

**Comment by az4aaz** [comment]
Initialement, c'était prévu pour garder un effet de surprise... Mais l'effet ne rend pas si bien, tu as raison, je fix ça dans le prochain commit !

**Comment by gablaxy** [comment]
Ok merci, je close l'issue
